### ISSUE TITLE
devkit.rb should be portable

### ISSUE THREAD

**Issue by jcsalomon** [oneclick/rubyinstaller#172]
I've got Ruby & DevKit on a flash drive, so the drive letter may change from one use to the next. I can set Ruby path in a batch file; _e.g._,

```
set Path=%~d0\ruby-2.0.0-p0-i386-mingw32\bin;%Path%
```

but `devkit.rb` has the drive letter hard-coded; _e.g._,

```
ENV['RI_DEVKIT'] = 'D:\\ruby-2.0.0-p0-i386-mingw32\\rubydev-4.7.2'
```

Is there a way to make this a relative path?

**Comment by johnnyshields** [comment]
Devkit will be retired in RubyInstaller2, think this can be closed?

**Comment by lamont-granquist** [comment]
Is RubyInstaller2 portable across drive letters?

The OP in this thread really wants to be able to load ruby on a flash drive and plug it into a random machine where it might be E: or F: or G: and have it just work without having to reinstall for that specific drive letter.  The fact that Devkit is mentioned is because in the current RubyInstaller that's the blocker to that functionality.  If you remove the thing named DevKit but the functionality isn't solved, then no, this issue isn't fixed.

**Comment by larskanis** [comment]
RubyInstaller2 with MSYS2 should be independent to the install path starting with rubyinstaller-2.4.1-1rc2 as provided [on appveyor](https://ci.appveyor.com/project/larskanis/rubyinstaller2-hbuor). Moreover it is documented in [the FAQ](https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-portable-install) now.

**Comment by lamont-granquist** [comment]
should be closable then

**Comment by luislavena** [comment]
As [indicated](https://github.com/oneclick/rubyinstaller/issues/172#issuecomment-292812473), RubyInstaller2 already provides the functionality requested.

Closing.
