### ISSUE TITLE
The unconditional 'devkit' check added to rubygems for native gem installation is too restricting

### ISSUE THREAD

**Issue by mcorino** [oneclick/rubyinstaller#259]
I have a native, *prebuilt*, gem that does not require compiling/linking any native code but does need some platform specific post-install configuration.
Since rubygems does not provide any decent post-install scripting support through the gem specification I use the extension support to do this inside a mkrf_conf*.rb type of file (followed up by a generated Rakefile).

This reasonably flexible and workable approach is spoiled on Windows using RubyInstaller installations by the above mentioned check that does *not* match any common practice with *nix distributions.

As said my gem does not require a devkit environment and I would very much like not to have to require my users to install any such kit before being able to install this gem.
Would it be possible to, at least, make this check optional some how?

**Comment by Azolo** [comment]
So, unfortunately the problem the Devkit is trying to solve is that the base Rubyinstaller installation doesn't meet the expectations that Ruby expects in a *nix environment. Nor do people want to develop simple gems and do extra work to get them to compile properly on Windows.

So the Devkit is developed to solve those problems in the simplest way possible for everyone. Unfortunately it does cause problems like this.

I've been scratching my head all day looking for a solution with a more exhaustive check. But there just isn't enough information provided in the `gemspec` to know if it will need a compiler or not. On the other hand not providing it would break the expectation other developers have in other environments without telling the user why it's not working.

That being said, it still doesn't solve your problem. If you have any suggestions, I'm all ears.

**Comment by mcorino** [comment]
First of all; I understand the problem you are trying to solve.
Only thing is; it starts of with the wrong assumption and will never be fullproof while blocking necessary functionality.

The assumption that a \*nix environment will *always* provide the necessary dev tools (make, gcc ...) is simply wrong. Just because in a lot of cases (with people doing regular development) this is true does not make it the standard. People running a *nix distro as a desktop replacement do not usually have these tools installed. I have a lot of thin *nix 'slave' VMs running that also do not all have the necessary tools installed. Not to mention the necessary development libraries!
In the *nix environment installing a gem with a native Ruby extension will happily attempt to build the extension and just as happily fail if I forgot to read it's install instructions (or did not know they were there) and provide me with information about what I might still need to install.
At least this does not prevent me from installing gems that use the exension builder mechanism for something that does not require the full range of dev tools and development libraries.

In the RubyInstaller devkit check the problem does not lie with the attempt to configure the Devkit before running the extension builder but with the decision to cancel the build unconditionally when this kit is not found (or some of it's tools are not detected) when there is absolutely no guarantee that the build will succeed in case you *did* detect the basic tools (or the Devkit installation) since at this point you have absolutely *no* idea what other requirements (dev libs) are in effect.

You now provide a flawed (at best) pre-install check that hardly provides better feedback compared to a failed extension builder which unconditionally blocks functionality that may not require what you check for at all!

Why not just try to configure the Devkit and (if you really must) output a warning if that fails but just let the build continue.

**Comment by Azolo** [comment]
So, the reality is that the RubyInstaller is just a Ruby distribution that is customized for ease of use on a Windows platform. Our current solution works for the vast majority of gems and use cases. If it's a burden for you to deploy, then consider deploying with a Ruby that you built yourself.

The current behavior is there for new users and cuts down on both their frustration and the limited amount of time we have to spend helping them. There's not a lot of support out there for running *Ruby on Windows* so this was the decision that was made.

Now, we get that it's not perfect. However, there's no support in `rubygems` to display a message on failure for gem installation. Nor is there a way to check to see if installation failed because we were missing the Devkit.

Now I get it, in your case it doesn't work. But what I will look at is how to tweak the current process to provide a solution in your workflow. I won't consider removing it entirely. If you can provide some constructive suggestions that don't completely gut the current behavior then I'll reopen the issue and discuss it.
