### ISSUE TITLE
Ruby does not work on WinXP

### ISSUE THREAD

**Issue by ksrik** [oneclick/rubyinstaller#271]
I installed Ruby 2.2.2 through RubyInstaller to the default directory, on WinXP SP3 (32 bit).

But ruby does not run, gives error:

`procedure entry point _gmtime64_s could not be located in the dynamic link library `

What is the problem here?

Regards,
srik

**Comment by Azolo** [comment]
Sorry, the current compiler toolchain actually fails on Windows XP and Windows Server 2003.

See #211 and #239 for more information.

**Comment by midas643** [comment]
Will it ever be supported again?

**Comment by Azolo** [comment]
That's a tricky question. I don't think there are plans to "officially" support it again. Since XP is past EoL, you have to stop somewhere.

However the fact that it stopped working on Windows XP is due to a issue with the compiler. When I update the compiler there's a good chance that it will start working again even though it's not official supported.

**Comment by midas643** [comment]
That's good to know. I'm waiting then for the news.

**Comment by ferfebles** [comment]
Any ETA for the compiler/DevKit upgrade?
I really would like to upgrade Ruby on Windows XP

**Comment by Azolo** [comment]
@ferfebles No, sorry.

**Comment by ferfebles** [comment]
I tried compiling Ruby 2.1 last year using a XP machine (#239), but I needed to disable networking in order to compile :-(

Thanks for replying and for your work in this project.

**Comment by Azolo** [comment]
If you try compiling with `mingwbuilds-64-4.7.3` by doing

    rake ruby22 DKVER=mingwbuilds-64-4.7.3

You might get better results.

**Comment by MarkDBlackwell** [comment]
@Azolo Basically following your suggestion, I successfully built Ruby 2.2.5p319 on my old 32-bit computer running Windows XP Home Edition, Service Pack 3, sporting an old (from 2003) processor without [SSE3](https://en.wikipedia.org/wiki/SSE3), while generally logged in with a Standard user (or Limited) account, not as an Administrator (excepting the steps to install programs or gems).

Here's how I did it:

Per the [README](https://github.com/MarkDBlackwell/rubyinstaller/blob/master/README.md), [Inno Setup](https://en.wikipedia.org/wiki/Inno_Setup) is required. (It generates the `rubyinstaller{{version}}.exe` file.)

Switching to an Administrator account, install its latest available Unicode version (currently 5.4.2) from [here](http://jrsoftware.org/isinfo.php). Include its preprocessor, and don't associate it with ".iss" files. Then append `;C:\Program Files\Inno Setup 5` to the PATH.

Microsoft's [HTML Help Workshop](https://en.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help) is required. (It builds the Ruby Help file.)

Again in the Administrator account, install the latest available version (currently 1.3) of its file, `htmlhelp.exe` from [here](https://www.microsoft.com/en-us/download/details.aspx?id=21138). Somehow, it's unnecessary to add this to the PATH.

From RubyInstaller's [downloads](http://rubyinstaller.org/downloads/) page, obtain and install the latest officially available 32-bit version of Ruby (I used rubyinstaller-2.0.0-p648.exe) to a path excluding spaces (I used `C:\progra\ruby`). Select the option to "Add Ruby executables to your PATH."

I selected the option "Install Tcl/Tk support," but not "Associate .rb and .rbw files with this Ruby installation."

Also there, select a RubyInstaller Development Kit "for use with Ruby 2.0 and above (32bits version only)." (I used DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe.) Download and install ("extract") it, following the [instructions](https://github.com/oneclick/rubyinstaller/wiki/Development-Kit), to a path excluding spaces (I used `C:\progra\ruby-install-devkit`).

Open a cmd.exe console window:

```
> cd C:\progra\ruby-install-devkit
> ruby dk.rb init
> ruby dk.rb review
> ruby dk.rb install
> gem update rdoc
> gem update --system
> gem update rake
> gem install rdoc_chm
> gem -v
2.6.6
```

After that, my gems included:

```
> gem list
rake (11.2.2)
rdoc (4.2.2)
rdoc_chm (3.1.0)
```

Switch back to your Standard user (or Limited) account, and open a [Git for Windows](https://git-for-windows.github.io/) command console. I ran it on [ConEmu](https://conemu.github.io/):

```
$ git clone https://github.com/oneclick/rubyinstaller.git
$ cd rubyinstaller

$ cat > override/my_overrides.rb
# Per:  http://rubyonwindowsguides.github.io/book/ch02-02.html

module RubyInstaller
  v = '2.2.5'
  Ruby22.version =          v
  Ruby22.files   = ["ruby-#{v}.tar.bz2"]
end
```

Typically, Git for Windows adds `/ming32/bin` or `/ming64/bin` to your PATH. (Do `echo $PATH` to see if it has done so.)

This gives RubyInstaller problems (currently). To avoid those problems, don't run the following steps under Git for Windows (especially `rake ruby22 dkver=mingw64-32-4.7.2`). Something in that directory makes the first `rake ruby22...` Rake task below abort (while creating `./config.status`). Instead, run the remaining steps under cmd.exe:

```
> rake clobber
> rake clean
> rake --tasks
> rake devkit:ls
```

I selected the latest version of mingwbuilds-32 (currently 4.7.3; mingwbuilds-64 failed):

```
> rake ruby22 dkver=mingwbuilds-32-4.7.3
> rake ruby22:package
> rake devkit sfx=1 dkver=mingwbuilds-32-4.7.3
```

Switch to an Administrator account and uninstall Ruby 2.0.0 (by clicking `C:\progra\ruby\unins000.exe`).

Uninstall the RubyInstaller DevKit (by deleting or renaming `C:\progra\ruby-install-devkit`).

Because my usual Windows user account was a Standard user (or Limited account; and not an Administrator), I didn't do `rake ruby22:install`.

Instead, in the directory `../rubyinstaller/pkg`, find the files `rubyinstaller{{version}}.exe` and `DevKit-{{version}}.exe`, and copy them to where you install things from.

Still in the Administrator account, install them (in the same way as above). Then (without switching accounts):

```
> cd C:\progra\ruby-install-devkit
> ruby dk.rb init
> ruby dk.rb review
> ruby dk.rb install
```

Restart the computer. After the BIOS message, hit F8 to obtain the Windows boot menu. Select the plain Safe Mode. Select the account you usually use for Administrative access (_not_ the one called here "Administrator") and log in. Click OK to proceed to Safe Mode.

Type Win-E to start the Windows Explorer and navigate to the folder, C:\progra\ruby. Right-click it.

Click the Security tab. If it says something like, "The permissions are incorrectly ordered" and "Click OK to continue and sort the permissions correctly," then click OK.

In the column, "Allow" and the row, "Users ({{computer name}}\Users," select the checkbox, "Full Control" and click Apply. When that's done, click OK.

Restart the computer and log in as your Standard user (or Limited) account. In a Git for Windows command console, do:

```
$ gem update --system
$ gem list json
$ gem list --remote --all "^json$"
```

Pick the next higher (teeny, if possible) version number than what's already installed. For me (up from 1.8.1), this was 1.8.2.

Per these [instructions](https://github.com/oneclick/rubyinstaller/wiki/Development-Kit#5-test-installation) to "confirm your Ruby environment is correctly using the DevKit" (and that the DevKit is working), do:

```
$ gem install json -v "1.8.2" --platform=ruby
```

**Comment by crazy-max** [comment]
@MarkDBlackwell I've got an error when i type the command `rake ruby22:package` :

```
rake aborted!
Don't know how to build task 'ruby22:docs'

Tasks: TOP => ruby22:package => ruby22:package:installer => pkg/rubyinstaller-2.2.5.exe
(See full trace by running task with --trace)
```

Do you have any idea ?

**Comment by crazy-max** [comment]
Ok solved by installing :

```
gem install rdoc -v 3.12
gem install rdoc_chm -v 3.1.0
```
