### ISSUE TITLE
Installers should be limited to Windows Vista and newer

### ISSUE THREAD

**Issue by sodabrew** [oneclick/rubyinstaller#280]
Following up from #54, it's years later and we should drop support for Windows XP by setting the new minimum to 0x0600.

For example, this enables use of GetTickCount64: https://msdn.microsoft.com/en-us/library/windows/desktop/ms724411%28v=vs.85%29.aspx

**Comment by Azolo** [comment]
Looking at #54 it looks like that was a reaction to changed in the Ruby  calls in Windows that were only compatible with XP and greater. If the Ruby core team make changes in the Ruby source, like using `GetTickCount64`, that cause incompatibility then updating minimum OS would make sense.

The current situation where RubyInstaller is incompatible with WinXp is because of incompatibility in the DevKit compiler and hopefully will be fixed next DevKit "upgrade".

**Comment by ferfebles** [comment]
Any ETA for the compiler/DevKit upgrade?
I really would like to upgrade Ruby on Windows XP
