### ISSUE TITLE
Support 2.2.4 and 2.1.8

### ISSUE THREAD

**Issue by deivid-rodriguez** [oneclick/rubyinstaller#300]
Could we get a new release supporting the new versions? Thanks!

**Comment by Azolo** [comment]
Working on it. =)

**Comment by deivid-rodriguez** [comment]
Thanks!! :santa:

**Comment by lmayorga1980** [comment]
:+1:

**Comment by Azolo** [comment]
Just a heads up, I'm having some problems with `2.1.8` bombing out in the middle of `make test-all` on  `TestSocket#test_closed_readmake`. I want to make sure it's not my build environment that's the problem before I release something broken because I screwed up. Once I'm comfortable that I didn't mess anything up, I'll finish up the final steps on releasing everything in the next few days.

**Comment by Fudoshiki** [comment]
Hello, when You can release 2.2.4?

**Comment by shevegen** [comment]
Same question that I have had like Fudoshiki :)

I am using 2.3.0 on linux at home but I have to support some windows laptop in 2 months.

If there is a way I can help let me know. I don't quite have a windows machine setup nearby but since that will be something that I may soon need myself, I can try to help hopefully.

**Comment by Azolo** [comment]
Hey guys, I got into a car accident and totaled my car on the 22nd. So, there have been some life things that I've had to take care of the last few days.

**Comment by lmayorga1980** [comment]
@Azolo You are more important that the update. Take care of yourself first.

Hope you are ok

**Comment by duytrung** [comment]
Thanks so much @Azolo, I'm waiting for your 2.3.0 release. All the best!

**Comment by ginolon** [comment]
@Azolo think about staying healthy, healthy mind in a healthy body. Thanks for your work.

**Comment by Azolo** [comment]
Just a heads up, I fixed the build environment problem(s). And I am rebuilding these versions as I get the time.

Thanks for being so patient.

**Comment by francesco-loreti** [comment]
any news?

**Comment by ewwink** [comment]
still waiting :1234:

**Comment by ginolon** [comment]
@ewwink and all, please don't ask for ETA. Please.

**Comment by Azolo** [comment]
Alright guys sorry it took so long. But they are released.

**Comment by ewwink** [comment]
thank you very much @Azolo

**Comment by lmayorga1980** [comment]
isn't 2.3.0 released already? Jk, 

Thanks. @Azolo
