### ISSUE TITLE
Ruby version 2.3.0 released. Where can I find the window binary version?

### ISSUE THREAD

**Issue by duytrung** [oneclick/rubyinstaller#302]
Hi all,
Ruby version 2.3.0 released as I found in ruby website: http://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/. Where can I find the window binary version?

Thanks!

**Comment by Azolo** [comment]
Hey, sorry there's going to be a delay in releases. See #300

**Comment by deivid-rodriguez** [comment]
Hi @Azolo , hope you're feeling better. I see you just released the other rubies, what about `2.3.0`? Planning on releasing it soon? Thanks!

**Comment by johnnyshields** [comment]
@Azolo hope you're recovering well. Would be great to know a rough ETA of the `2.3.0` release, or alternatively, if there's another maintainer whom you could designate to help. Would be great to see the community step up and help out when one member is in a bind.

**Comment by Azolo** [comment]
@johnnyshields @deivid-rodriguez Thanks, I'm doing pretty good. The real problem is working around schedules and such because I don't have a vehicle. But right now there really aren't any other maintainers, and there's a lot of manual work that goes into a release at the moment. So as I get time and such I try to get some stuff done on it.

**Comment by espinosa** [comment]
Hi @Azolo, it's nice to hear you are good! Can you list the work that need to be done, so maybe we can help you. I have build ruby23 but test-all give more than 70 errors. Is there some doc that describe the release process ?

**Comment by Azolo** [comment]
@espinosa See if [this post](https://groups.google.com/d/msg/rubyinstaller/E4QqFiO5mHE/EoqkHwpOHgAJ) help out any.

**Comment by Startouf** [comment]
Any news on that ? I still don't see 2.3 on rubyinstaller.org

**Comment by Sega100500** [comment]
When Ruby 2.3 for windows will be released?

**Comment by Azolo** [comment]
I finally have some free time so I'm shooting for this weekend.

**Comment by deivid-rodriguez** [comment]
Hi @Azolo ! Any progress? Thanks!

**Comment by johnnyshields** [comment]
Guys--at the moment this is held up because there are failing tests when building Ruby 2.3 on windows. What we need:
1) Someone to checkout PR #305, run the windows build, and document the failing cases
2) Report the failing cases to the Ruby core team bug tracker

**Comment by Azolo** [comment]
Some not so great family stuff came up, I've got it built and packaged but I need to write release notes, upload everything, and update the website.

I promise I haven't forgotten about this. But sometimes things in life are just brutal.

**Comment by jdlars** [comment]
Thanks for the regular updates @Azolo! 2.3 is still pretty fresh and I am sure people are anxious to try it out, but if impatience is getting the best of anybody, let us all remember how easy it is to develop in a VM like https://www.virtualbox.org/ ... If you want to try out some of the cool new features, you can at least get your fix while you wait during this final stretch.

**Comment by LordMalkev** [comment]
Any news? Any way to help?

**Comment by johnnyshields** [comment]
Read my comment above.

**Comment by Azolo** [comment]
So, a couple of things.

1) I finally got some time to get everything together and release ruby 2.3.0.
You can download it on [bintray][1] or from the [rubyinstaller downloads page][2].

2) I would really like to thank everyone in the community for helping out in all the different ways everyone has. Especially @windwiny,@johnnyshields, and @shirosaki for working on the errors that came up in the Ruby tests. This should realistically make Ruby better for everyone on Windows.

I think this is the most community involvement in a very long time and even thought I've been busy and it is kind of my fault because I haven't been able to do release this version in a timely manner, I still want to thank everyone for everything they have done,

[1]: https://bintray.com/oneclick/rubyinstaller/rubyinstaller/2.3.0
[2]: http://rubyinstaller.org/downloads

**Comment by johnnyshields** [comment]
@Azolo, @windwiny, and @shirosaki deserve the credit, I'm just the piano man.

@Azolo, just to clarify which Ruby tag or ref did you release from? Were any tests failing on it?

Great work again and thanks guys!

**Comment by Azolo** [comment]
@johnnyshields We only build RubyInstaller releases off of the Ruby release versions. Which means this is the version that was released in December.

**Comment by RoopeHakulinen** [comment]
Thank you for your great job on this. It is greatly appreciated and 2.3.0 support was very crucial to my business. 

Could you please update the website as last part of the release since I (and probably many others) was polling for it to find out if the release was made. :)

@Azolo is perhaps the right person to address this?

**Comment by Azolo** [comment]
@RoopeHakulinen Which part did it forget to update? 😓

**Comment by RoopeHakulinen** [comment]
I was looking for it at http://rubyinstaller.org/

**Comment by Azolo** [comment]
@RoopeHakulinen Oops, I'll update it when I get a chance.

Thanks.

**Comment by RoopeHakulinen** [comment]
No worries, just bringing it up :+1:
