### ISSUE TITLE
HTTPS site triggers mixed content warning

### ISSUE THREAD

**Issue by strugee** [oneclick/rubyinstaller#309]
The HTTPS site triggers mixed content warnings, which should be fixed. This is the first step to having an HTTPS-only site.

**Comment by Azolo** [comment]
@strugee Indeed it is. But unless someone feels like helping out I've been swamped lately.

I'm months behind on releases, and things don't look like they will get any better for me for a couple months. So it's a want, but other things are more important. =/

**Comment by strugee** [comment]
@Azolo happy to help if you can point me at the source. I found oneclick/rubyinstaller.org, but that seems to be a new codebase.

**Comment by Azolo** [comment]
It is actually deployed in a CMS. There have been a couple pushes to rewrite the site into a Sinatra app and then as a Jekyll site.

But they are both time consuming endeavors so they didn't ever get finished.

The assets are served from a cdn which is where you get that warning from.

**Comment by strugee** [comment]
Ah, okay. So nowhere except oneclick/rubyinstaller.org, correct?

**Comment by Azolo** [comment]
Correct, that repo is what it could be! But not currently what it is.

**Comment by luislavena** [comment]
Hello,

rubystaller.org website is run via a Radiant CMS (Rails application) run on Heroku. The theme used by the website can be found in the following repository:

https://github.com/oneclick/website-html

However, it has been adapted to be run in Radiant (including their tagging and partials) which might not result in a straightforward update (but not impossible).

However, in order to have `rubyinstaller.org` as secured domain, a valid SSL will be need to be issued. While Let's Encrypt might provide that, Heroku charges $20/month for that support.

An alternative will be replace the current website for something more manageable (there has been several attempts, custom Rack application, a Hugo one and others).

Moving away from Heroku and perhaps static website might result in something more easy for people to contribute.

While I remain non-involved with Ruby (or RubyInstaller) anymore, wanted to chime here since a cost on Heroku SSL might be end being paid from my account (since I believe I'm still owner of the application). This is still true for Amazon S3 and CloudFront charges that arrive to my inbox on a monthly basis.

Of course, as always, contributions (in the form of code, a working website, anything) are welcome.

Cheers.

**Comment by XhmikosR** [comment]
Since you are using Cloudflare, just use relative links for all assets and force HTTPS in Cloudflare panel.

Everything will be served from CF then.

**Comment by strugee** [comment]
@XhmikosR that doesn't solve Cloudflare to Heroku connection security, unless I'm missing something.

Also, are you sure they're using Cloudflare? Or did you (like me) misread "CloudFront"?

**Comment by XhmikosR** [comment]
Well the connection between Cloudflare and the server is another issue. I
simple pointed out that they can use Cloudflare's SSL. And yeah I'm pretty
sure they use Cloudflare. Just check the headers.

**Comment by luislavena** [comment]
This should be working now: https://rubyinstaller.org

**Comment by luislavena** [comment]
Notes on the changes:

- Updated `stylesheets` and `scripts` snippet to use `https` on all the resources
- Updated some templates that have `img` references to point to `https` resources
- Obtained a SSL certificate for `cdn.rubyinstaller.org` via Amazon Certificate Manager to use with the Cloudfront setting

Please note that I didn't enable `HSTS` via Cloudflare since once done there is no easy way to workaround that until the given time window expires.

Cheers.

**Comment by XhmikosR** [comment]
Or you could use Cloudflare instead of your own CDN, thus no need for you to pay for a certificate. And you could even host the site on GitHub pages if you don't want to pay a server.

Just some thoughts.

**Comment by luislavena** [comment]
@XhmikosR 

Site is built using Radiant, which is a CMS built on top of Ruby on Rails. Is not an static website that can be hosted by GitHub pages.

App server is provided on a free Heroku dyno.

No cert has been bought, Amazon issues SNI certs to be used with Cloudfront distributions.

Traffic has been moving away of the Cloudfront CDN and only static assets remains. These could go away by solving the website issue I mentioned before.

There has been fruitless efforts of porting RubyInstaller to a static website (that could work with GitHub pages), however no volunteer has stepped up and took the challenge.

**Comment by XhmikosR** [comment]
It should be pretty easy, though. I could have a go when I have some free time, if there's a repo with the latest sources.

**Comment by luislavena** [comment]
@XhmikosR the critical part is always finding that **free time**, which has always been the OSS challenge. Any contribution is welcome.

**Comment by XhmikosR** [comment]
@luislavena: agreed. Anyway, so if there's a repo with the current source code, I could have a look later.

**Comment by luislavena** [comment]
@XhmikosR there is none for current, please see my comment from [March 4](#issuecomment-192327048)
