### ISSUE TITLE
Issues with Ruby on Windows

### ISSUE THREAD

**Issue by stibra** [oneclick/rubyinstaller#311]
Hi,
I have one problem running the script on Windows on any version of Ruby, it works without problems on Linux or OSX. It works also with cygwin on Windows.

Can someone check this please?
Thanks,

Ratko
[get_ca_cert.txt](https://github.com/oneclick/rubyinstaller/files/151046/get_ca_cert.txt)

**Comment by sroller** [comment]
which script?

**Comment by stibra** [comment]
I have attached the ruby code in the issue: get_ca_cert.txt

**Comment by sroller** [comment]
It's not my area of expertise but I don't this is the right place to ask for help. If you really want a response, then you shouldn't s just ask "can someone check this". You should lay out what you have done so far, what has worked, was has not. What did you try. Break down the script to the smallest possible amount of code etc. After you've done all of that I'd go to http://stackoverflow.com for the help request.

**Comment by stibra** [comment]
Waiting for the developers to describe the problem, sorry for that.

**Comment by zmajstor** [comment]
error `bignum too big to convert into 'long' (RangeError)` is in the method `#to_der` from class `OpenSSL::ASN1` which is somewhere between ruby and OpenSSL library

this error doesn't show if you run script on OS X, Linux or Cygwin ruby, it breaks only on ruby from rubyinstaller v2.2.4 on Windows

**Comment by sroller** [comment]
Do you run the 64bit version?

what's the output of ```ruby -v```?

**Comment by sroller** [comment]
BTW: this issue here https://github.com/net-ssh/net-ssh/issues/235 looks similar to yours.

**Comment by stibra** [comment]
The same issue on 32-bit and 64-bit Ruby. This fails all the time.

**Comment by stibra** [comment]
My colleague found the problem, it was caused by long validity period for the certificates. 
In the line https://github.com/ruby/openssl/blob/master/ext/openssl/ossl_asn1.c#L86 
Instead of NUM2LONG, NUM2LL have to be used!
Can you include this fix in the next Ruby release?

Thanks,

Ratko

**Comment by stibra** [comment]
This is actually well know "year 2038"  bug (https://en.wikipedia.org/wiki/Year_2038_problem), obviously fixed on the Linux, but not on Windows.

**Comment by zmajstor** [comment]
@sroller this is the test which fails on Windows: https://gist.github.com/zmajstor/8a3d458f28f14585aed1
test will pass on Windows if you set `valid_until` for cert below year 2038

this test is variation of test from ruby repo: https://github.com/ruby/ruby/blob/trunk/test/openssl/test_asn1.rb#L5

**Comment by luislavena** [comment]
Hello,

This looks like to be a problem with upstream (Ruby and OpenSSL) and while affects RubyInstaller (for being Windows), is nothing that RubyInstaller can control (see [CONTRIBUTING](https://github.com/oneclick/rubyinstaller/blob/master/CONTRIBUTING))

I recommend reporting this to Ruby bug tracker instead:

https://bugs.ruby-lang.org/

**Comment by zmajstor** [comment]
@luislavena, please note that this test is failing **only** on Windows: https://gist.github.com/zmajstor/8a3d458f28f14585aed1 
my colleague has created issue related to this problem: https://github.com/ruby/openssl/issues/48
but I seriously doubt that somebody who doesn't run Windows will care to change codebase

**Comment by luislavena** [comment]
@zmajstor RubyInstaller is a free and contribution based project.

The role of the project is provide installers to make things easier, but not go and patch every single library out there to make it work with Windows, which is a humongous task by itself.

Since your co-worker was able to correct the issue (as indicated in the linked issue), I recommend this be reported back to Ruby issue tracker and even better, provide a patch or a pull request that will allow developers to easily merge this back.

I had stepped up to respond here because I believe @Azolo has been away due personal reasons, but that still doesn't mean is RubyInstaller role to get this sorted out inside Ruby (see my link to contributing).

If you believe this is RubyInstaller role, then you're welcome to join the team and step up by doing the above mentioned tasks (report and get it sorted on Ruby) or extend the RubyInstaller codebase to run this OpenSSL patch during build phase.

Either way, the code for all these options is freely available and the channels to submit those contributions will welcome those without hesitation.

Cheers.

**Comment by zmajstor** [comment]
@luislavena, I perfectly understand your point of view, and I highly appreciate your contribution to RubyInstaller (together with all other maintainers) ... I'm just saying that this problem is reproducible only on Windows platform, that's all

**Comment by luislavena** [comment]
@zmajstor there are Windows developers on Ruby Core that can take care of evaluate and merge that patch and get that included for next release of Ruby.

**Comment by zmajstor** [comment]
that would be great! thanks
