### ISSUE TITLE
Ruby 1.9.3p551 not working on Windows XP embedded,

### ISSUE THREAD

**Issue by realvz** [oneclick/rubyinstaller#312]
I've installed Ruby 1.9.3p551 on Windows XP Embedded and it installs fine but crashes on launching Ruby.exe 

The version of OS on the thin client is:
Windows XP Embedded Standard Service Pack 3 x86

Windows Visual C++ 2008 Redistributable is also installed.

`C:\Ruby193\bin>ruby: [BUG] Segmentation fault
'ruby:' is not recognized as an internal or external command,
operable program or batch file.
 
C:\Ruby193\bin>ruby 1.9.3p551 (2014-11-13) [i386-mingw32]
ruby: [BUG] Segmentation fault
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]
 
-- Control frame information -----------------------------------------------
c:0001 p:0000 s:0002 b:0002 l:001eec d:001eec TOP
 
 
-- C level backtrace information -------------------------------------------
 
-- Other runtime information -----------------------------------------------
 
* Loaded script: ruby
 
* Loaded features:
 
    0 enumerator.so
 
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html`
 
 
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.`

**Comment by luislavena** [comment]
Hello,

Windows XP embedded is not a supported platform as it has removed support for several components that might be required by regular Windows applications to work.

Windows XP SP3 might be still supported for certain versions (based on the compiler used) but embedded variants are problematic.

Since none of the team have Windows Embedded to test this, there isn't much we can do to assist.

Please comment back if you have further debugged the issue.

Cheers.
