### ISSUE TITLE
GEM_HOME and GEM_PATH not set by Rubyinstaller, is this default behavior?

### ISSUE THREAD

**Issue by jjgh** [oneclick/rubyinstaller#319]
Hi, on Windows 7 64bit I am observing that after installing Ruby 2.3.0 64bit, using latest RubyInstaller, GEM_PATH and GEM_HOME env. variables are not set and this is giving me some problems with SSL root certificate file and other minor issues. Now, I know that I can easily set those vars manually, but what I am trying to understand here is if there is some kind of bug in RubyInstaller which prevents it to set them, in case this is the default expected behavior.

So, is RubyInstaller setting those environment variables (and possibly others) by default?
Based on this answer I will have to diagnose other kinds of problems with my system (where I also have installed JRuby 9.0.0.0. which is also in path...).
Thanks.

**Comment by Azolo** [comment]
No, `GEM_HOME` and `GEM_PATH` are managed by Ruby itself unless explicitly asked to do so otherwise.

We considered at one point using `GEM_HOME` and `GEM_PATH` to install gems `npm` style in a different directory, but since binary `gems` are super common and have breaking changes in every minor release we decided against it.
