### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by vais** [oneclick/rubyinstaller#321]
I may be getting the wrong impression, but is this project still alive and kickin'?
[Edit] I mean, *if* it's in trouble, what are the problems and how can *I* help?

**Comment by Azolo** [comment]
Hey, sorry. This project is still very much alive, but the time I have to work on Open Source work has been cut dramatically.

Therefore I work on the releases when I get time and try to make time when I can.


In terms of things people can do to help out: 

- Look at the RDoc-chm project and get it updated to use the newer Rdoc templates so I don't have to patch RDoc locally for a release.
- Try to get a continuous delivery platform that can build releases somewhere in the cloud so that I can just download them and upload them to Bintray and do the other busy work that comes with a release.
- Implement a new rubyinstaller.org website that can handle just uploading a yaml file and can either recompile and deploy (Jekyll) or dynamically update a page easily (Sinatra).

**Comment by vais** [comment]
Good to hear, @Azolo, thank you. I can only imagine the challenges of keeping RubyInstaller up to date, please keep up the great work! I hope to be able to pitch in soon...

In the meantime, the reason I opened this issue is that all of the installers available from RubyInstaller at this time are for known "buggy" versions of Ruby:

* `2.3.0` really should be `2.3.1` ([bug fix release, available sine April 26, 2016](https://www.ruby-lang.org/en/news/2016/04/26/ruby-2-3-1-released/))
* `2.2.4` really should be `2.2.5` ([bug fix release, available sine April 26, 2016](https://www.ruby-lang.org/en/news/2016/04/26/ruby-2-2-5-released/))
* `2.1.8` really should be `2.1.9` ([bug fix release, available sine March 30, 2016](https://www.ruby-lang.org/en/news/2016/03/30/ruby-2-1-9-released/))

Hope there's nothing holding these up (blocking issues?) other than lack of time to make the releases? (Which is a perfectly valid reason and completely understandable, don't get me wrong).

**Comment by Azolo** [comment]
@vais Merely lack of time. Work has been stressful, and I don't work primarily on a Windows Machine anymore so I have to make extra time to get to the releases outside of what I used to do as part of my workflow.

As for issues, it takes at least 45 minutes of work outside of compiling for every release. The things above would shorten that time and the CI part would mean that I wouldn't even need to compile personally and everyone could get a version as soon as possible.

I wish I had more/better news than that but it is what it is. =/

**Comment by MarkDBlackwell** [comment]
See #271 for a solution.

**Comment by kybu** [comment]
Thanks for the new release.

Speaking of CI, the only one supporting Windows for free I could find is following : https://www.appveyor.com/

I can have a look how to integrate ruby installer with it.

**Comment by vais** [comment]
:tada: Thank you, @Azolo!!

**Comment by MarkDBlackwell** [comment]
On Windows XP (and presumably on Windows 2003 server) the official Ruby 2.2.5 [release](https://bintray.com/oneclick/rubyinstaller/download_file?file_path=rubyinstaller-2.2.5.exe) (32-bit) fails.

An "Entry Point Not Found" message pops up for `ruby.exe`: "The procedure entry point _gmtime64_s could not be located in the dynamic link library msvcrt.dll." This is #211.

See this [comment](https://github.com/oneclick/rubyinstaller/issues/271#issuecomment-232534767) (in #271) for workaround.
