### ISSUE TITLE
Ruby 2.3.1 released 26 Apr 2016 - when will be released windows installer?

### ISSUE THREAD

**Issue by Sega100500** [oneclick/rubyinstaller#326]
Ruby 2.3.1 released 26 Apr 2016 - when will be released windows installer?

**Comment by leonhooijer** [comment]
It has already been requested. Please look at #318, #320 and #325.

**Comment by Sega100500** [comment]
@leonhooijer 
Where it in
http://rubyinstaller.org/downloads/
???

**Comment by leonhooijer** [comment]
We have to wait for one of the repository owners to merge the PR. 

In the meantime you can clone the repository from [leonhooijer/rubyinstaller](https://github.com/leonhooijer/rubyinstaller) and build the version you require. If you are not able to build it on your own I can do it for you.

**Comment by Sega100500** [comment]
@leonhooijer 
> We have to wait for one of the repository owners to merge the PR.
When it happends?

> If you are not able to build it on your own I can do it for you.
No. I can't able to built it on my own.

**Comment by Sega100500** [comment]
@leonhooijer 
Please just put rubyinstaller for windows on
http://rubyinstaller.org/downloads/

**Comment by leonhooijer** [comment]
I cannot upload to the website because I am not the owner. I built an installer for Ruby 2.3.1 (32 bits) for you which you can download [here](https://onedrive.live.com/redir?resid=CD2A4CD09A599DA3!1640637&authkey=!ADEbC3yb5m0DFZc&ithint=file%2cexe).

MD5: 0204208b6f4aad7772565a097eefdf61
SHA256: e431b02983e4d17d8c91be6cd48233be743a8ccd449aa253c4e3b518f6c5c9f6

**DISCLAIMER**: not tested, I am not responsible for any damage if it is not working correctly. If you do not trust it wait for an release on [rubyinstaller.org](http://rubyinstaller.org/).

If you have any more questions just let me know.

**Comment by Sega100500** [comment]
@leonhooijer 
Many THANKS but I still wait for OFFICIAL release. But also 64-bit

Every time need wait long-long-long time after oficial release of Ruby for rubyinstaller is out.
It is very sad!

**Comment by Azolo** [comment]
If you haven't been following along the past few months, I've been really busy.

If you want faster releases, here are some things that can help out.
https://github.com/oneclick/rubyinstaller/issues/321#issuecomment-219296160

Closing this because of the other issues open.
