### ISSUE TITLE
README should show which build combinations work for which versions of Windows

### ISSUE THREAD

**Issue by MarkDBlackwell** [oneclick/rubyinstaller#333]
README should show which build combinations work for which versions of Windows

The README should tell us under which combinations of circumstances RubyInstaller is known to work (as the [downloads](http://rubyinstaller.org/downloads/) page hints), such as:

1. For the various Ruby base versions (as supported by RubyInstaller);
1. For 32-bit versus 64-bit machines;
1. Using the compilation environments: tdm, mingw, mingwbuilds, and mingw64 in all their various versions (as used by RubyInstaller);
1. On [Windows](https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions) XP Home (NT 5.1), versus Windows Vista (NT 6.0) or later (etc.);
1. On Windows Server 2003 (NT 5.2), versus Windows Server 2008 (NT 6.0) or later (etc.); and
1. Generated on Linux, for each of the above Windows versions.

As you know, for each combination of circumstances, eventually Continuous Integration (CI) testing can report this status.

"You can embed status images (also known as badges or icons) that show the status of your build into your README," says a Travis CI [webpage](https://docs.travis-ci.com/user/status-images/) (for example).

Older hardware isn't abandoned by Ruby, and it shouldn't be abandoned by RubyInstaller, either.

**Comment by Azolo** [comment]
The inability to handle Windows XP was actually a bug in the compiler toolchain.  However, the cost of changing the compiler toolchain is quite high and the audience for Windows XP is lower.

But the other problem arises where the resources to support the kind of thing you're asking for is basically the members of the community and me. I personally haven't had the luxury of using RubyInstaller for anything outside of building RubyInstaller in about a year.

So if someone in the community wanted to step up and maintain and support such a list and the problems that pop up then they are welcome to, though that kind of thing is probably better in the Wiki.

If someone asks me, then I don't mind sharing the information necessary to make it work. However, I don't want to put it in an official medium because I personally can't support any problems that come up from building and using Ruby without the regular release DevKit.

I'm sorry, but I'm only one person whom has other responsibilities outside of RubyInstaller that have to take priority.
