### ISSUE TITLE
Ruby 2.3.3, 2.2.6

### ISSUE THREAD

**Issue by XhmikosR** [oneclick/rubyinstaller#344]
https://www.ruby-lang.org/en/news/2016/11/21/ruby-2-3-3-released/

https://www.ruby-lang.org/en/news/2016/11/15/ruby-2-2-6-released/

@Azolo: just pinging you in case you missed it.

**Comment by Azolo** [comment]
Thanks, I saw and am working on them.
I'll get them released in the next couple of days.

**Comment by XhmikosR** [comment]
@Azolo: ping.

It seems rubygems changed their pem file or something so when one starts with vanilla 2.3.1 they can't update. I had to download cacert.pem myself in order for gem update to work on a fresh install.

**Comment by luislavena** [comment]
@XhmikosR you can manually update RubyGems to latest version:

http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages

Just replace `2.6.7` with `2.6.8` in the instructions and the download link.

**Comment by XhmikosR** [comment]
@luislavena Like I said, I just specified the cacert.pem location.

But if this issue happens to others, it means things are pretty broken, and they require manual steps to circumvent the issue, unless a new release is out.

**Comment by luislavena** [comment]
@XhmikosR is not RubyInstaller policy to release new installers on every change of RubyGems but instead lock to the specific Ruby version.

In this particular case there are new versions, but again, building installers and testing takes time.

I've stepped out of RubyInstaller 2 years ago and showing up now to respond these open issues since many have been poking me to my inbox lately (like **a lot**)

It appears Justin (@Azolo) has been having some personal issues, which is why there hasn't been new releases.

RubyInstaller has been and remains a contributor effort, so if we don't have the time to work on it, then no work is done.

While I do understand where you're coming from with your statement, there isn't much I can do about it.

If a company wants to sponsor time for someone to work on these releases and keep them up-to-date I guess will be highly welcome.

I've no personal issue with another individual(s) or a company to step up and take care of these things. I still have access to all the resources (and still paying for some of the costs of it) and can grant access to the interested ones.

**Comment by XhmikosR** [comment]
I'm aware of all this, I'm just poking him, in case he forgot about it.

I too am a maintainer of many projects and I'm aware of the cons believe me.

**Comment by ilessy** [comment]
Even Ruby on windows can keep up with the release, it is very slow on windows compared to ruby on Mac because of MinGW I think.  I wish Ruby can support windows officially just as PHP and Python.

**Comment by vais** [comment]
@ilessy 

> it is very slow on windows compared to ruby on Mac because of MinGW I think

I don't think so, see e.g. [Building PostgreSQL on Windows for Performance](http://www.openscg.com/2016/02/building-postgresql-on-windows-for-performance). I quote:

> For years, there has been the ability to replicate the Linux build experience on Windows with the Mingw project, but historically the resulting binaries have been significantly slower than the binaries produced by the Microsoft compiler. Since I last played with compliers on Windows, I have been pleasantly surprised that the open source build tools have caught up with the commercial tools and in some ways surpassed them.

The author goes on to demonstrate with benchmarks that the MinGW GCC build of postgresql was not only as performant as MSVC, but in fact 3.8% faster. Of course the only way to see if the same applies to Ruby is to benchmark yourself against the MS compiler (good luck) or at least against a Mac or Linux with the same exact hardware specs as the Windows counterpart, both running the same exact version of Ruby.

**Comment by daniel-rikowski** [comment]
Is there documentation on which steps have to be performed for a _new_ Ruby version? I've looked at the Wiki but all I found was targetet at the Ruby versions already present in RubyInstaller.

In other words: What needs to be done in RubyInstaller when a new version of Ruby is released? (Besides running the various rake tasks, compiling, uploading, ...)

**Comment by luislavena** [comment]
@daniel-rikowski in README:

- https://github.com/oneclick/rubyinstaller/#7-second-quick-start
- https://github.com/oneclick/rubyinstaller/#build-task-examples

There is no release documentation specifically, so free free to take a look to the task and potentially document the process.

**Comment by luislavena** [comment]
@ilessy as @vais stated, the usage of MinGW (mingw-w64 in this case) is not the reason of Ruby being slow.

Back in 2011 worked on this issue, did a presentation on Ruby Conf Argentina. Here are the slides (spanish) but I guess you can get the idea:

- https://speakerdeck.com/luislavena/tirando-ruby-por-la-ventana

And my blog post:

http://blog.mmediasys.com/2011/11/26/rubyconf-argentina-and-fenix/

And here a recording of the talk:

https://vimeo.com/38561561

However, even after all that work, Ruby carries a lot of legacy on how things are done that resulted on this patch not getting applied entirely due backward compatibility and resulted in not so great speed up.

All the back and forth here:

https://bugs.ruby-lang.org/issues/6836

> Normally we should not depend on the path normalization function of File.expand_path.
> Each program should perform peculiar safing processing which each needs.
> Therefore, I think that the approach of Rack may be better, too.
> 
> However, it is very difficult to write safe code because there are too many traps in the file system of Windows.
> It's impossible for non-Windows programmers in particular.
> For instance, your WEBrick patch calls Win32 API with DL, but Unix programmers will not know Win32 API.
> Therefore, we made decision of pushing all the troubles in File.expand_path.
> We expected to help to write safe code in almost all cases.
> 
> Possibly this was not a good message.
> Much program depending on File.expand_path may have been made in the world.
> It's the reason why I am very cowardly to change the behavior of File.expand_path.

---

To your other points:

> it is very slow on windows compared to ruby on Mac because of MinGW I think.

See above, facts over theories, MinGW is not the culprit.

> I wish Ruby can support windows officially just as PHP and Python.

I also wish Windows was a first class platform for Ruby and that it didn't rely on contributor effort to perform releases and such. But reality over the last 10 years has proven that what I wish rarely comes true.

**Comment by ilessy** [comment]
@luislavena Thanks for your kind reply. Maybe I should give up the "Ruby on Windows" idea.  At least for CRuby.

**Comment by Azolo** [comment]
Unfortunately, I don't have the luxury of using RubyInstaller day-to-day anymore. So when there is a new release I have to make time to actually sit down and build it.

I've tried to pawn off the build process to VMs but there seems to be a problem where hypervisor environments don't get the same results as a regular Windows environment. I spent time on that rabbit hole until it exhausted me.

So at the moment, it takes about 1.5 hours to build, test, and package a version of Ruby. Then adding the quirks like making sure we have the correct version of Innoinstaller, getting HTMLHelp for the CHM, and the `rdoc_chm` workaround for building docs for Ruby 2.3. Most of my times is spent away from my PC these days and when something goes wrong the process just gets that much longer.

So while I sincerely enjoy doing this, but I'm unable to commit the time I used to or the time I want to make the project better because I don't use the project consistently anymore. There are tons of things that anyone can do to make the process better, but not without taking a deep dive into the project to understand the problems.

I'm getting the releases out when I can, but it's a time consuming process that I have to actually make time for these days.

**Comment by Azolo** [comment]
My last message was directed more or less at @daniel-rikowski and it was half me misreading what he said. 🙊

@ilessy I find that slowness "on Windows" is pretty much a moot point. If I wanted something fast then I wouldn't use Ruby on any platform. After developing on both, I can say that my productivity was marginally better on a Mac because of the tools I used from the community not because Ruby was slower.

My problem is that Ruby isn't my preferred tool anymore. Most of the powerful scripting stuff I used to use Ruby for I now use PowerShell. If I need to build a web application I prefer Phoenix over Rails these days. If I need to build a static site I will still use Ruby and Jekyll.

I don't think speed between platforms is a viable reason to "give up" on a language. If you need something to be "faster" then I would question why you used Ruby in the first place.

I may be wrong, but I don't think any seasoned Rubyist has shunned Windows just because it was slower.

**Comment by luislavena** [comment]
Thank you @Azolo for taking the time and respond.

Guess that leave RubyInstaller in the lookup for a maintainer in order to release these new versions.

It will also require the upgrade of bundled RubyGems to latest version, specially due the changes in certs in rubygems.org.

If anyone is willing to accept such challenge, either as individual or backed by the company they work for (even better), please respond to this conversation.

Thank you.

**Comment by Azolo** [comment]
@luislavena Finding a new maintainer is probably a good idea. At least someone that has the time to build and release the various versions.

I'm in the process of getting everything released for 2.2.6 and 2.3.3, but it's been a hodgepodge of time around my PC that is setup to build RubyInstaller that's taken 3 weeks.
The Ruby 2.4 release around Christmas will be probably be another extended release like this one, where it comes down to when I get long blocks of time it takes to build.

> It will also require the upgrade of bundled RubyGems to latest version, specially due the changes in certs in rubygems.org.

The `stdlib` version of RubyGems in 2.2.6 and 2.3.3 both have the updated cert so that isn't an issue.
