### ISSUE TITLE
Need WSA installer for Nano Server

### ISSUE THREAD

**Issue by woodie** [oneclick/rubyinstaller#363]
Nono Server is the future, but Nano Server has no graphics libraries so MSI installers won't work. We need a WSA installer for Nano Server for Ruby and DevKit.

https://blogs.technet.microsoft.com/nanoserver/2015/11/19/hands-on-packaging-and-installing-your-first-windows-server-apps-on-nano-server/

**Comment by Azolo** [comment]
I don't think it's a good idea. But that's because of what a WSA is meant to be, not because Ruby shouldn't be on Nano.

First of all, to the best of my knowledge, a WSA package is meant to be a full application. Meaning that your ideal WSA package will be:

- Ruby (No Compile Tools)
- Compiled Gems
- Project
- Service Registration

You could (I think?) have just Git and Ruby + DevKit installed, then setup and build your project. I don't think that's a good idea though. The point of Nano is to have a containerized application that can pushed out and expected to work properly.

I think the purpose was to have every WSA be specific to an application not to the tools. In other words, I don't think it's a RubyInstaller type project. If anything it would be a separate project to automate those things for people.

As an aside, a WSA that's specific purpose was to build Ruby WSAs (if you can use WiX) is probably possible.

**Comment by woodie** [comment]
Yes, I can use xcopy to manually put Ruby and DevKit an instance of Nano, as proposed by Jeffrey Snover‏: https://twitter.com/jsnover/status/865177689811951616). That's not what I'm trying to accomplish. I'm installing Ruby and DevKit into a Docker base image so that the entire world can invoke whatever version of Ruby they want, using a tag, without ever having to do anything manually.

Creating such an image is easy with [windowsservercore](https://github.com/woodie/windowsservercore-ruby/blob/master/Dockerfile), but not with [nanoserver](https://github.com/woodie/nanoserver-ruby/blob/master/Dockerfile) because exe and msi installers won't work, and my nanoserver example fails because 7Zip4Powershell currently requires some component not included with Nano.
 
The windowsservercore images is a 3GB behemoth, so we really want to create a nanoserver-ruby base image that will be around 30MB.

**Comment by Azolo** [comment]
Ahhh, I see. You're doing it through `Docker` containers and their build system. This is still outside the scope of RubyInstaller and the new [RubyInstaller2 project][1]. Which is changing the DevKit installation process.

I have a rant about how ridiculous a Ruby Docker container can be because of the dependence on native extensions, but that's a different story,

I don't have any where I can setup and test creating Windows containers and don't feel like setting one up to play around, but try using the [`7za.exe`  command line utility][2]. I think all the `dll`s are statically linked in that release so it may fix the errors.

If you mention me in another repo you're trying to get this working in then I can probably help you get it working, but I don't think building a WSA is the right plan.

[1]: https://github.com/oneclick/rubyinstaller2
[2]: http://www.7-zip.org/a/7za920.zip

**Comment by woodie** [comment]
Well, we can expand the zip file, but that 7za.exe doesn't work on Nano.

Here's what the Dockerfile looks like.

```
FROM microsoft/nanoserver

RUN mkdir C:\\tmp

ADD http://www.7-zip.org/a/7za920.zip C:\\tmp
RUN powershell -command \
    Expand-Archive -LiteralPath C:\\tmp\\7za920.zip -DestinationPath C:\\7-Zip
RUN setx PATH %PATH%;C:\7-Zip -m
```
