### ISSUE TITLE
Inconsistent IO when reading files with \r\n line endings

### ISSUE THREAD

**Issue by ubswrk** [oneclick/rubyinstaller#376]
**NOTE**: This project is for Ruby version 2.3 and older.
For Ruby versions >= 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller2/issues/new ).

## What problems are you experiencing?
`IO.foreach` with any params and `IO.read` without a length argument both remove `\r` characters. `IO.read` doesn't remove them when given a length limit argument.

## Steps to reproduce
Try reading a file with `\r\n` line endings. Note that `IO.read` produces different results when providing and not providing the length limit

## What's the output from `ruby -v`?
...

**Comment by larskanis** [comment]
Yes this seems to be inconsistent, but the difference is due to specifying the length in __bytes__. When a length is given, the output of read is always in binary encoding and without any character conversions. This is expected and [documented behavior](https://ruby-doc.org/core-2.4.1/IO.html#method-i-read).

Therefore using `read` with a length should be done in binary mode only, to be more consistent. You can then use `IO.binread` as a shortcut.
